### PR TITLE
no category exists when exporting to ynab

### PR DESCRIPTION
**Pull request by orentet**
just enter the category manually. no need to stop the whole process.

### CODE REVIEW

**Comment by baruchiro** [comment]
Hi @orentet, welcome!
Sorry, but I don't have a YNAB account, and I'm not sure if we must set categories or not. It seems a good change, but we will wait for @brafdlog approval.

Thanks again, and talk with us if you want to help.

**Comment by orentet** [comment]
I'll be happy to help.

**Review by brafdlog — APPROVED** [review]
Welcome :)

I originally threw this error so I would see that there is a mismatch in the mapping. But for the current state of the project, your change makes sense

**Comment by baruchiro** [comment]
@orentet I think you're welcome to merge it. Do you have permission for that?

**Comment by orentet** [comment]
no, you can add me as collaborator and i'll merge it.

**Comment by baruchiro** [comment]
@orentet Thanks for your contribution!
I don't have a YNAB account, and @brafdlog was in the middle of a great improvement in the YNAB config area, but for now, he is a little busy. His work is in this branch: https://github.com/brafdlog/budget-tracking/tree/ynabConfigHelper
Can you take a look and see if you can complete his work?

**Pull request merged**
